<?php 
 $select_config = [];
    $select_config['wechat_type']=[
        ['code'=>1,'title'=>'未认证订阅号'],
        ['code'=>2,'title'=>'认证订阅号'],
        ['code'=>3,'title'=>'未认证服务号'],
        ['code'=>4,'title'=>'认证服务号'],
        ['code'=>5,'title'=>'企业号'],  
    ];  
    $select_config['wechat_click_type']=[
        ['code'=>1,'type'=>'click','title'=>'点击'],
        ['code'=>2,'type'=>'view','title'=>'跳转'],
        ['code'=>3,'type'=>'scancode_waitmsg','title'=>'调用扫一扫'],
        ['code'=>4,'type'=>'pic_photo_or_album','title'=>'调用相机或者相册'],
        ['code'=>5,'type'=>'location_select','title'=>'获取坐标位置'],
        //['code'=>6,'type'=>'media_id','title'=>'获取图片'], 
        //['code'=>7,'type'=>'view_limited','title'=>'获取图文'],
        ['code'=>8,'type'=>'miniprogram','title'=>'获取小程序'],
    ];
    $select_config['wechat_msg_type']=[
        ['code'=>0,'type'=>null,'title'=>'请选择信息类型'],
        ['code'=>1,'type'=>'text','title'=>'文本'],
        ['code'=>2,'type'=>'img','title'=>'图片'],
        ['code'=>3,'type'=>'news','title'=>'图文'],
        ['code'=>4,'type'=>'video','title'=>'视频'],
        ['code'=>5,'type'=>'voice','title'=>'音频'],
        ['code'=>6,'type'=>'key_words','title'=>'关键字'],
        ['code'=>7,'type'=>'sub_button','title'=>'显示二级菜单'],
        ['code'=>8,'type'=>'card','title'=>'卡券']
    ];
    $select_config['wechat_card_type']=[
        ['code'=>0,'type'=>null,'title'=>'请选择卡券类型'],
        ['code'=>1,'type'=>'GROUPON','title'=>'团购券'],
        ['code'=>2,'type'=>'CASH','title'=>'代金券'],
        ['code'=>3,'type'=>'DISCOUNT','title'=>'折扣券'],
        ['code'=>4,'type'=>'GIFT','title'=>'兑换券'],
        ['code'=>5,'type'=>'GENERAL_COUPON','title'=>'优惠券']
    ];
    $select_config['wechat_code_type']=[
        ['code'=>0,'type'=>null,'title'=>'请选择核销码类型'],
        ['code'=>1,'type'=>'CODE_TYPE_QRCODE/CODE_TYPE_BARCODE','title'=>'扫码/输码核销'],
        ['code'=>2,'type'=>'CODE_TYPE_ONLY_QRCODE','title'=>'仅适用于扫码核销'],
        ['code'=>3,'type'=>'CODE_TYPE_TEXT','title'=>'仅适用于输码核销'],
        ['code'=>4,'type'=>'CODE_TYPE_NONE','title'=>'线上核销']
    ];
    $select_config['wechat_card_color']=[
        ['code'=>"Color010",'color'=>'#63b359'],
        ['code'=>"Color020",'color'=>'#2c9f67'],
        ['code'=>"Color030",'color'=>'#509fc9'],
        ['code'=>"Color040",'color'=>'#5885cf'],
        ['code'=>"Color050",'color'=>'#9062c0'],
        ['code'=>"Color060",'color'=>'#d09a45'],
        ['code'=>"Color070",'color'=>'#e4b138'],
        ['code'=>"Color080",'color'=>'#ee903c'],
        ['code'=>"Color081",'color'=>'#f08500'],
        ['code'=>"Color082",'color'=>'#a9d92d'],
        ['code'=>"Color090",'color'=>'#dd6549'],
        ['code'=>"Color100",'color'=>'#cc463d'],
        ['code'=>"Color101",'color'=>'#cf3e36'],
        ['code'=>"Color102",'color'=>'#5E6671']
    ];
return $select_config;
